#!/usr/bin/env node

const AWS = require("aws-sdk");
AWS.config.update({ region:
  process.env.CDK_DEPLOY_REGION ||
  process.env.CDK_DEFAULT_REGION ||
  process.env.AWS_REGION ||
  "us-east-1"
});
const cfn = new AWS.CloudFormation();

const getStackOutput = async (StackName, key) => JSON.parse(
  (await cfn.describeStacks({ StackName }).promise())
    .Stacks
    .map((stack) => stack.Outputs
      .find((output) => output.OutputKey === key))
    .filter((it) => it)
    .shift()
    .OutputValue);

async function main() {
  const [firebaseProjectId] = process.argv.slice(2);
  if (!firebaseProjectId) {
    throw new Error("Specify Firebase project ID");
  }
  const baseConfig = await getStackOutput(
    `${firebaseProjectId}-ApiStack`,
    "AmplifyConfigOutput"
  );
  console.log(JSON.stringify(baseConfig, null, 2));
}

main().catch(console.error);
